frontend:
  build: ./trade-tariff-frontend
  command: bundle exec unicorn -p 3017
  links:
   - api
  ports:
   - "3017:3017"
  volumes:
    - ./trade-tariff-frontend/src:/app
  environment:
   - TARIFF_API_HOST=http://api:3018
api:
  build: ./trade-tariff-backend
  command: bundle exec unicorn -p 3018
  links:
   - mysql
   - redis
   - elasticsearch
  ports:
   - "3018:3018"
  volumes:
    - ./trade-tariff-backend/src:/app
  environment:
   - DATABASE_URL=mysql2://tariff:tariff@mysql:3306
   - GDS_SSO_STRATEGY=real
admin:
  build: ./trade-tariff-admin
  command: bundle exec unicorn -p 3046
  links:
   - admindb
   - api
   - signonotron2
  ports:
   - "3046:3046"
  volumes:
    - ./trade-tariff-admin/src:/app
  environment:
   - DATABASE_URL=mysql2://tariff_admin:tariff_admin@admindb:3306
   - GDS_SSO_STRATEGY=real
   - PLEK_SERVICE_TARIFF_API_URI=http://api:3018
   - PLEK_SERVICE_SIGNON_URI=http://dockerhost:3016
signonotron2:
  build: ./signonotron2
  command: bundle exec unicorn -p 3016
  links:
   - signondb
   - redis
  ports:
   - "3016:3016"
  volumes:
    - ./signonotron2/src:/app
  environment:
   - DATABASE_URL=mysql2://signonotron2:signonotron2@signondb:3306
mysql:
  image: tutum/mysql:5.5
  ports:
    - 3306
  environment:
   - MYSQL_USER=tariff
   - MYSQL_PASS=tariff
   - ON_CREATE_DB=tariff_development
admindb:
  image: tutum/mysql:5.5
  ports:
    - 3306
  environment:
   - MYSQL_USER=tariff_admin
   - MYSQL_PASS=tariff_admin
   - ON_CREATE_DB=tariff_admin_development
signondb:
  image: tutum/mysql:5.5
  ports:
    - 3306
  environment:
   - MYSQL_USER=signonotron2
   - MYSQL_PASS=signonotron2
   - ON_CREATE_DB=signonotron2_development
redis:
  image: convox/redis
  ports:
    - 6379
elasticsearch:
  image: elasticsearch
  ports:
    - 9200
